/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-11 02:10:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp._0509과제.마켓컬리;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kurly_005fsignup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <section id=\"section1\">\r\n");
      out.write("            <div className=\"container\">\r\n");
      out.write("                <div className=\"gap\">\r\n");
      out.write("                    <div className=\"title\">\r\n");
      out.write("                        <h2>회원가입</h2>\r\n");
      out.write("\r\n");
      out.write("                        <p><span><i>*</i>필수입력사항</span></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div className=\"content\">\r\n");
      out.write("                        <form  name=\"signup_form\" id=\"signUpForm\" method=\"post\" action=\"./kurly_signup_action.jsp\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label htmlFor=\"userId\">아이디<i>*</i></label>\r\n");
      out.write("                                        <div className=\"center-box\">\r\n");
      out.write("                                            <input \r\n");
      out.write("                                                type=\"text\" \r\n");
      out.write("                                                maxLength={16} \r\n");
      out.write("                                                name=\"user_id\" \r\n");
      out.write("                                                id=\"userId\" \r\n");
      out.write("                                                placeholder=\"아이디를 입력해주세요\" \r\n");
      out.write("                                            />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label htmlFor=\"userPw1\">비밀번호<i>*</i></label>\r\n");
      out.write("                                        <div className=\"center-box\">\r\n");
      out.write("                                            <input \r\n");
      out.write("                                                type=\"password\"  \r\n");
      out.write("                                                maxLength={16} \r\n");
      out.write("                                                name=\"user_pw\" \r\n");
      out.write("                                                id=\"userPw1\" \r\n");
      out.write("                                                placeholder=\"비밀번호를 입력해주세요\" \r\n");
      out.write("                                            />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label htmlFor=\"userPw2\">비밀번호확인<i>*</i></label>\r\n");
      out.write("                                        <div className=\"center-box\">\r\n");
      out.write("                                            <input \r\n");
      out.write("                                                type=\"password\"  \r\n");
      out.write("                                                maxLength={16} \r\n");
      out.write("                                                name=\"user_pw\" \r\n");
      out.write("                                                id=\"userPw2\" \r\n");
      out.write("                                                placeholder=\"비밀번호를 한번 더 입력해주세요\" \r\n");
      out.write("                                            />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label htmlFor=\"userName\">이름<i>*</i></label>\r\n");
      out.write("                                        <div className=\"center-box\">\r\n");
      out.write("                                            <input \r\n");
      out.write("                                                type=\"text\" \r\n");
      out.write("                                                name=\"user_name\" \r\n");
      out.write("                                                id=\"userName\" \r\n");
      out.write("                                                placeholder=\"이름을 입력해주세요\" \r\n");
      out.write("                                            />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label htmlFor=\"userEmail\">이메일<i>*</i></label>\r\n");
      out.write("                                        <div className=\"center-box\">\r\n");
      out.write("                                            <input \r\n");
      out.write("                                                type=\"email\" \r\n");
      out.write("                                                name=\"user_email\" \r\n");
      out.write("                                                id=\"userEmail\" \r\n");
      out.write("                                                placeholder=\"이메일을 입력해주세요\" \r\n");
      out.write("                                            />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <button  \r\n");
      out.write("                                            type=\"button\"\r\n");
      out.write("                                        >중복확인</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label htmlFor=\"userHp\">휴대폰<i>*</i></label>\r\n");
      out.write("                                        <div className=\"center-box\">\r\n");
      out.write("                                            <input \r\n");
      out.write("                                                type=\"text\"  \r\n");
      out.write("                                                maxLength={11} \r\n");
      out.write("                                                name=\"user_hp\" \r\n");
      out.write("                                                id=\"userHp\" \r\n");
      out.write("                                                placeholder=\"숫자만 입력해주세요\" \r\n");
      out.write("                                            />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <button  type=\"button\">인증번호 받기</button>\r\n");
      out.write("                                        <button type=\"button\">번호 인증</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label htmlFor=\"userAddress1\">주소<i>*</i></label>\r\n");
      out.write("                                        <div className=\"center-box\"> \r\n");
      out.write("                                            <input \r\n");
      out.write("                                                type=\"text\" \r\n");
      out.write("                                                name=\"user_address\" \r\n");
      out.write("                                                id=\"userAddress1\" \r\n");
      out.write("                                                placeholder=\"주소 입력\" \r\n");
      out.write("                                            <h5>샛별배송</h5>\r\n");
      out.write("                                            <h6>배송지에 따라 상품 정보가 달라질 수 있습니다.</h6>\r\n");
      out.write("                                            />\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                        <button \r\n");
      out.write("                                            type=\"button\"\r\n");
      out.write("                                        >재검색</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>                                 \r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label>성별</label>\r\n");
      out.write("                                        <div className=\"center-box gender\">\r\n");
      out.write("                                            <label><input type=\"radio\" name=\"user_gender\" id=\"userMale\" value=\"남자\" />남자</label>\r\n");
      out.write("                                            <label><input type=\"radio\" name=\"user_gender\" id=\"userFemale\" value=\"여자\"  />여자</label>\r\n");
      out.write("                                            <label><input type=\"radio\" name=\"user_gender\" id=\"userNone\" value=\"선택안함\" />선택안함</label>\r\n");
      out.write("                                        </div>                                            \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                                <li>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                        <label>생년월일</label>\r\n");
      out.write("                                        <div className=\"center-box birth\">\r\n");
      out.write("                                            <div className=\"birth-box\">\r\n");
      out.write("                                                <ul>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <input \r\n");
      out.write("                                                            type=\"text\" \r\n");
      out.write("                                                            maxLength={4} \r\n");
      out.write("                                                            name=\"user_birth\" \r\n");
      out.write("                                                            id=\"userBirth\" \r\n");
      out.write("                                                            placeholder=\"YYYY\"\r\n");
      out.write("                                                        /></li>\r\n");
      out.write("                                                    <li><i>/</i></li>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <input \r\n");
      out.write("                                                            type=\"text\" \r\n");
      out.write("                                                            maxLength={2} \r\n");
      out.write("                                                            name=\"user_birth\" \r\n");
      out.write("                                                            id=\"userBirth>\" \r\n");
      out.write("                                                            placeholder=\"MM\" \r\n");
      out.write("                                                        /></li>\r\n");
      out.write("                                                    <li><i>/</i></li>\r\n");
      out.write("                                                    <li>\r\n");
      out.write("                                                        <input \r\n");
      out.write("                                                            type=\"text\" \r\n");
      out.write("                                                            maxLength={2} \r\n");
      out.write("                                                            name=\"user_birth\" \r\n");
      out.write("                                                            id=\"userBirth\" \r\n");
      out.write("                                                            placeholder=\"DD\" \r\n");
      out.write("                                                        /></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>                                      \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>    \r\n");
      out.write("\r\n");
      out.write("                                <li>\r\n");
      out.write("                                        <label>추가입력사항<i>*</i>\r\n");
      out.write("                                            <input type=\"radio\" name=\"user_add\" id=\"userAdd\" value=\"친구초대 추천인 아이디\">친구초대 추천인 아이디\r\n");
      out.write("                                            <input type=\"radio\" name=\"user_add\" id=\"userAdd\" value=\"참여 이벤트명\">참여 이벤트명\r\n");
      out.write("                                            <h6>가입 후 7일 내 첫 주문 배송완료 시, 친구초대 이벤트 적립금이 지급됩니다.</h6>\r\n");
      out.write("                                            <h6>\r\n");
      out.write("                                                추천인 아이디와 참여 이벤트명 중 하나만 선택 가능합니다.<br/>\r\n");
      out.write("                                                가입 이후는 수정이 불가능 합니다.<br/>\r\n");
      out.write("                                                대소문자 및 띄어쓰기에 유의해주세요.\r\n");
      out.write("                                            </h6>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <label>이용약관동의<i>*</i>\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"user_chk\" id=\"chk1\" value=\"전체 동의합니다.\">전체 동의합니다.                                            \r\n");
      out.write("                                        <h5>선택항목에 동의하지 않은 경우도 회원가입 및 일반적인 서비스를 이용할 수 있습니다.</h5>\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"user_chk\" id=\"chk2\" value=\"이용약관 동의.\">이용약관 동의  \r\n");
      out.write("                                        <input type=\"checkbox\" name=\"user_chk\" id=\"chk3\" value=\"개인정보 수집∙이용 동의.\">개인정보 수집∙이용 동의 \r\n");
      out.write("                                        <input type=\"checkbox\" name=\"user_chk\" id=\"chk4\" value=\"무료배송, 할인쿠폰 등 혜택/정보 수신 동의\">무료배송, 할인쿠폰 등 혜택/정보 수신 동의\r\n");
      out.write("                                        <h6>동의 시 한 달간 [5%적립] + [2만원 이상 무료배송] 첫 주문 후 안내</h6>\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"user_chk\" id=\"chk5\" value=\"본인은 만 14세 이상입니다.(필수)\">본인은 만 14세 이상입니다.(필수)\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <button type=\"submit\">가입하기</button>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
