/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-25 07:50:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.국민건강보험._0424_005fJSP_005f국민건강보험폼;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>국민건강보험 회원가입폼</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        #wrap {width :100%;}\r\n");
      out.write("        #wrap form {width: 900px; height:1500px; margin: 0 auto; }\r\n");
      out.write("        #wrap form label {display:flex; align-items: center; padding : 15px 0; position: relative; border-bottom: 1px solid #e1e3e6;}\r\n");
      out.write("        #wrap form label span {position: absolute;  top:28px; left:0;font-size: 15px; letter-spacing: -1px;}\r\n");
      out.write("        #wrap form label .bunsil {position: absolute;  top:20px; left:0;font-size: 15px; letter-spacing: -1px;}\r\n");
      out.write("        #wrap form label input {margin: 0 0 0 200px; background-color: #fff2f2; border:1px solid #ffd7d2; height:38px; line-height: 40px; border-radius: 5px; padding: 0 0 0 8px; font-size: 15px;\r\n");
      out.write("        letter-spacing: -0.5px;}\r\n");
      out.write("        #wrap form label .saup1 {width: 189px; margin: 0 0 0 200px; background-color: #fff2f2; border:1px solid #ffd7d2; height:38px; line-height: 40px;}\r\n");
      out.write("        #wrap form label .saup2 {width: 716px; margin: 0 0 0 200px; background-color: #f1f1f1; border:1px solid #ccc; height:38px; line-height: 40px;}\r\n");
      out.write("        #wrap form label .id {width: 189px; margin: 0 0 0 200px; background-color: #fff2f2; border:1px solid #ffd7d2; height:38px; line-height: 40px;}\r\n");
      out.write("        #wrap form label .pw {width: 536px; margin: 0 0 0 200px; background-color: #fff2f2; border:1px solid #ffd7d2; height:38px; line-height: 40px;}\r\n");
      out.write("        #wrap form label .hp {width: 338px; margin: 0 0 0 200px; background-color: #fff2f2; border:1px solid #ffd7d2; height:38px; line-height: 40px;}\r\n");
      out.write("        #wrap form label button {margin: 0 15px; height: 38px; background-color: #fff;border: 1px solid #69727e; cursor: pointer; border-radius: 4px; letter-spacing: -1px;}\r\n");
      out.write("        #wrap form label .dawi {margin: 0 0 0 200px;}\r\n");
      out.write("        #wrap form label .dawi2 {margin: 0 0 0 15px; background-color: #f1f1f1; border:1px solid #ccc; width:189px;}\r\n");
      out.write("        #wrap form label .que {width: 275px;margin: 0 0 0 200px; height:38px; background-color: #fff2f2; border: 1px solid #ffd7d2;}\r\n");
      out.write("        #wrap form .ga {position:absolute; top:95%; left:50%; background-color: #ee0700; color:#fff;font-size: 15px;height:48px;width:80px; padding:0 20px; border:0; border-radius: 4px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <div class=\"top\">\r\n");
      out.write("            <a href=\"./signup_view.jsp\">가입목록</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form autocomplete=\"off\" name=\"signup_form\" id=\"signUpForm\" method=\"\r\n");
      out.write("        post\" action=\"signup_write.jsp\">\r\n");
      out.write("                <label for=\"memu1\"><span>사업장관리번호</span><input class=\"saup1\" type=\"text\" name=\"memu1\" id=\"memu1\" placeholder=\"\"><button>사업장관리번호 확인</button></label>\r\n");
      out.write("                <label for=\"memu2\"><span>사업장기호</span><input class=\"saup2\" type=\"text\" name=\"memu2\" id=\"memu2\" placeholder=\"사업장관리번호확인 버튼을 클릭하여 검증하시면 자동입력 됩니다.\"></label>\r\n");
      out.write("                <label for=\"memu3\"><span>단위사업장기호</span><button class=\"dawi\">단위사업장 검색</button><input class=\"dawi2\" type=\"text\" name=\"memu3\" id=\"memu3\" placeholder=\"\"><button>가입여부 확인하기(실명확인)</button></label>\r\n");
      out.write("                <label for=\"memu4\"><span>아이디</span><input class=\"id\" type=\"text\" name=\"memu4\" id=\"memu4\" placeholder=\"영문+숫자 6~10자 이내\"><button>아아디 중복검색</button></label>\r\n");
      out.write("                <label for=\"memu5\"><span>비밀번호</span><input class=\"pw\" type=\"text\" name=\"memu5\" id=\"memu5\" placeholder=\"영문+숫자+특수문자(!@#$)각 1자 이상 포함하여 9~12자 이내\"></label>\r\n");
      out.write("                <label for=\"memu6\"><span>비밀번호확인</span><input class=\"pw\" type=\"text\" name=\"memu6\" id=\"memu6\" placeholder=\"영문+숫자+특수문자(!@#$)각 1자 이상 포함하여 9~12자 이내\"></label>\r\n");
      out.write("                <label for=\"memu7\">\r\n");
      out.write("                    <span class=\"bunsil\">비밀번호 분실시 확인<br>질문</span><select class=\"que\" name=\"memu7\" id=\"memu7\">\r\n");
      out.write("                            <option value=\"질문을 선택하세요\">질문을 선택하세요</option>\r\n");
      out.write("                            <option value=\"나의 아버지 성함은 ?\">나의 아버지 성함은 ?</option>\r\n");
      out.write("                            <option value=\"나의 그리운 고향은 ?\">나의 그리운 고향은 ?</option>\r\n");
      out.write("                            <option value=\"나의 첫째아이 이름은 ?\">나의 첫째아이 이름은 ?</option>\r\n");
      out.write("                            <option value=\"나의 초등학교 이름은 ?\">나의 초등학교 이름은 ?</option>\r\n");
      out.write("                            <option value=\"나의 보물 제1호는 ?\">나의 보물 제1호는 ?</option>\r\n");
      out.write("                            <option value=\"기억에 남는 추억의 장소는 ?\">기억에 남는 추억의 장소는 ?</option>\r\n");
      out.write("                            <option value=\"나의 인생 좌우명은 ?\">나의 인생 좌우명은 ?</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </label>\r\n");
      out.write("                <label for=\"memu8\"><span class=\"bunsil\">비밀번호 분식시 확인<br>답변</span><input class=\"pw\" type=\"text\" name=\"memu8\" id=\"memu8\" placeholder=\"조희답변은 띄어쓰기 포함 10자이내\"></label>\r\n");
      out.write("                <label for=\"memu9\"><span>전화번호</span><input class=\"hp\" type=\"text\" name=\"memu9\" id=\"memu9\" placeholder=\"-(하이픈)없이 입력 (예:010123456789)\"></label>\r\n");
      out.write("                <label for=\"memu10\"><span>업무담당자명</span><input type=\"text\" class=\"pw\" name=\"memu10\" id=\"memu10\" placeholder=\"사업장의 소속된 직장 가입자 직원 또는 대표자\"></label>\r\n");
      out.write("                <label for=\"memu11\"><span>이메일</span><input class=\"hp\" type=\"text\" name=\"memu11\" id=\"memu11\" placeholder=\"이메일을 입력하세요\"></label>\r\n");
      out.write("                <label for=\"memu12\"><span>소식지 수신여부</span>\r\n");
      out.write("                    <input type=\"radio\" name=\"memu12\" id=\"memu12\" value=\"받음\"> 받음 \r\n");
      out.write("                    <input type=\"radio\" name=\"memu12\" id=\"memu12\" value=\"안받음\"> 안받음\r\n");
      out.write("                </label>\r\n");
      out.write("            <button class=\"ga\" type=\"submit\">가입</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
