/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-10 05:46:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.홍성민_005f국민._0502과제.국민;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 // 폼 전송 받은 한글 깨짐현상 셋팅 인코딩
    request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <div id=\"section\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"gap\">\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <h2>회원가입</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                        <div class=\"row1\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><em>01</em> 약관동의</li>\r\n");
      out.write("                                <li><img src=\"./img/arrow-progress-on-2.png\" alt=\"\"><em>02</em> 가입정보입력</li>\r\n");
      out.write("                                <li><img src=\"./img/arrow-progress-on.png\" alt=\"\"><em>03</em> 가입완료</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row2\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                개인(직장가입자)이 아닌 <strong>사업장업무를 위한 회원가입</strong>입니다.\r\n");
      out.write("                                사업장관리번호 및 단위 사업장 기호가 다른 경우에는 각각 회원가입을 하셔야 합니다\r\n");
      out.write("                                예) 건설현장 사업장마다 사업장관리번호가 각각 적용되오니 회원가입도 각각 하셔야 해당 업무를 이용하실 수 있습니다.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row3\">\r\n");
      out.write("                            <p><i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i>표는 필수 입력 사항이며, [동일아이디검색] 및 [가입여부확인] 버튼을\r\n");
      out.write("                                반드시 눌러주세요.</p>\r\n");
      out.write("                            <form name=\"bohum_form\" id=\"bohumForm\" method=\"POST\" action=\"insert_action.jsp\">\r\n");
      out.write("                                <label for=\"menu1\">\r\n");
      out.write("                                    <span>아이디<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" name=\"menu1\" id=\"menu1\" placeholder=\"영문+숫자 6~10자 이내\" required>\r\n");
      out.write("                                    <button type=\"button\">아이디 중복검색</button>\r\n");
      out.write("                                    \r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label for=\"menu2\">\r\n");
      out.write("                                    <span>사업장관리번호<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" name=\"menu2\" id=\"menu2\" required>\r\n");
      out.write("                                    <button type=\"button\"class=\"btn1\">사업장관리번호 확인</button>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn2\">사업장관리번호 확인방법</button>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label for=\"menu3\">\r\n");
      out.write("                                    <span>사업장기호<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" name=\"menu3\" id=\"menu3\" placeholder=\"사업장관리번호확인 버튼을 클릭하여 검증하시면 자동입력 됩니다.\" required>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label for=\"menu4\" class=\"menu3\">\r\n");
      out.write("                                    <span>단위사업장기호<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>  \r\n");
      out.write("                                    <button type=\"button\">단위사업장검색</button>                                  \r\n");
      out.write("                                    <input type=\"text\" name=\"menu4\" id=\"menu4\" required>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <button type=\"button\">가입여부 확인하기(실명확인)</button>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                \r\n");
      out.write("                                <label for=\"menu5\">\r\n");
      out.write("                                    <span>비밀번호<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" name=\"menu5\" id=\"menu5\" placeholder=\"영문+ 숫자+특수문자(!@#$) 각 1자 이상 포함하여 9~12자 이내\" required>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label for=\"menu6\">\r\n");
      out.write("                                    <span>비밀번호확인<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" name=\"menu6\" id=\"menu6\" placeholder=\"영문+ 숫자+특수문자(!@#$) 각 1자 이상 포함하여 9~12자 이내\" required>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label for=\"menu7\">\r\n");
      out.write("                                    <span>비밀번호 분실 시 확인 질문<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <select name=\"menu7\" id=\"menu7\">\r\n");
      out.write("                                        <option value=\"질문선택\">질문선택</option>\r\n");
      out.write("                                        <option value=\"사람인가요?\">사람인가요?</option>\r\n");
      out.write("                                        <option value=\"이상형\">이상형</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label for=\"menu8\">\r\n");
      out.write("                                    <span>비밀번호 분실 시 확인 답변<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" name=\"menu8\" id=\"menu8\" placeholder=\"조회 답변은 띄어쓰기 포함 10자 이내\" required>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label for=\"menu9\">\r\n");
      out.write("                                    <span>전화번호<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" name=\"menu9\" id=\"menu9\" placeholder=\"“-(하이픈)” 없이 입력 (예 : 01012345678)\" required>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label for=\"menu10\">\r\n");
      out.write("                                    <span>업무담당자명<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" name=\"menu10\" id=\"menu10\" placeholder=\"사업장의 소속된 직장 가입자 직원 또는 대표자\" required>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label for=\"menu11\" class=\"menu11\">\r\n");
      out.write("                                    <span>이메일<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <input type=\"text\" name=\"menu11\" id=\"menu11\" \r\n");
      out.write("                                        required>\r\n");
      out.write("                                    <select name=\"email\" id=\"email\">\r\n");
      out.write("                                        <option value=\"직접입력\">직접입력</option>\r\n");
      out.write("                                        <option value=\"hanmail\">hanmail</option>\r\n");
      out.write("                                        <option value=\"naver\">naver</option>\r\n");
      out.write("                                        <option value=\"gmail\">gmail</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <div class=\"menu12\">\r\n");
      out.write("                                    <span>소식지 수신여부<i><img src=\"./img/ico-compulsory.png\" alt=\"\"></i></span>\r\n");
      out.write("                                    <label for=\"okno\">\r\n");
      out.write("                                        <input type=\"radio\" name=\"menu12\" id=\"ok\" value=\"받음\" required>받음\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <label for=\"\">\r\n");
      out.write("                                        <input type=\"radio\" name=\"menu12\" id=\"no\" value=\"안받음\" required>안받음(공단의 다양한 소식을 무료로 만나보세요)\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"btn-box\">\r\n");
      out.write("                                    <em><button type=\"submit\" class=\"btn3\">확인</button></em>\r\n");
      out.write("                                    <button type=\"button\">취소</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
