/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-06 06:42:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp._0406_005f자바_005fJSP_005f프로그래밍;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 스타벅스_005f공지사항_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>스타벅스 공지사항</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        #main{ width: 100%;}\r\n");
      out.write("        #main .container{ width: 1100px; height: 100%; margin: 0 auto;}\r\n");
      out.write("        #main .container .gap{}\r\n");
      out.write("        #main .container .gap .title{ width: 100%; padding: 0 0 100px 0;  text-align: center;}\r\n");
      out.write("        #main .container .gap .title h2{ font-size: 36px;     font-weight: 700;   color: #000;}\r\n");
      out.write("\r\n");
      out.write("        #main .container .gap .content{ justify-content: center;\r\n");
      out.write("                    align-items: center;}\r\n");
      out.write("        #main .container .gap .content table{ width: 100%;\r\n");
      out.write("                        border-collapse: collapse;\r\n");
      out.write("                        text-align: center; }\r\n");
      out.write("        #main .container .gap .content table thead{\r\n");
      out.write("            padding: 10px 0 0 0;\r\n");
      out.write("            border-top: 1px solid #000;\r\n");
      out.write("            border-bottom: 1px solid #000;\r\n");
      out.write("            padding: 17px 0;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: #222;\r\n");
      out.write("        }\r\n");
      out.write("        #main .container .gap .content table thead tr{\r\n");
      out.write("            padding: 10px 0 0 0;\r\n");
      out.write("            border-top: 1px solid #000;\r\n");
      out.write("            border-bottom: 1px solid #000;\r\n");
      out.write("            padding: 17px 0;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: #222;\r\n");
      out.write("        }\r\n");
      out.write("        #main .container .gap .content table thead tr th{\r\n");
      out.write("            padding: 10px 0 0 0;\r\n");
      out.write("            border-top: 1px solid #000;\r\n");
      out.write("            border-bottom: 1px solid #000;\r\n");
      out.write("            padding: 17px 0;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: #222;                    \r\n");
      out.write("        }\r\n");
      out.write("        #main .container .gap .content table tbody{\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        #main .container .gap .content table tbody tr{\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #main .container .gap .content table tbody tr td{\r\n");
      out.write("            padding: 17px 0 17px 20px;\r\n");
      out.write("            border-top: 1px solid #f7f7f7;\r\n");
      out.write("            border-bottom: 1px solid #999;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            /* padding: 17px 0; */\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: #666;   \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h1>스타벅스 공지사항</h1>\r\n");
      out.write("\r\n");
      out.write("    <div id='main'>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h2>공지사항</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>No</th>\r\n");
      out.write("                                <th>제목</th>\r\n");
      out.write("                                <th>날짜</th>\r\n");
      out.write("                                <th>조회수</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("\r\n");
      out.write("                                ");

                                    
                                    int[] num1 = {425, 424, 423, 422, 421, 420, 419, 418, 417, 416};
                                    String[] str = {"시스템 개선 및 서비스 점검 안내", "시스템 개선 및 서비스 점검 안내", "탄소중립포인트 인센티브 지급 기준 안내", "스타벅스 코리아 사칭 홈페이지 및 이메일 주의 안내", "Summer 시즌 사이렌 오더 음료 기본 설정 변경 안내", "시스템 개선 및 서비스 점검 안내", "탄소중립실천포인트제 도입 안내", "	영상정보처리기기 운영방침 / 위치정보 이용약관 / 개인정보처리방침 이용약관 개정 안내", "시스템 개선 및 서비스 점검 안내", "	설 연휴 스타벅스 딜리버스 운영 안내"};
                                    String[] str2 = { "	2023-04-04	", "2023-03-27	", "2023-03-23	", "2023-03-20	", "	2023-03-17", "	2023-02-17", "2023-02-02	", "	2023-02-02", "	2023-01-27	", "	2023-01-20	"};
                                    int[] num2 = { 1479, 1720, 25999,3705, 21037, 3377, 20653, 2135,1879, 9036};
                                    for(int i=0; i<num1.length; i++){
                                        out.println("<tr>" );
                                        out.println("<td>" + num1[i] + "</td>");
                                        out.println("<td>" + str[i] + "</td>");
                                        out.println("<td>" + str2[i] + "</td>");
                                        out.println("<td>" + num2[i] + "</td>");
                                        out.println("</tr>" );
                                    }
                            
                                 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!--     \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    for(int i=0; i<str.length; i++){
        out.println(str[i] + "<td>");
    }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

        


    
      out.write("\r\n");
      out.write("    ");

    for(int i=0; i<str2.length; i++){
        out.println(str2[i] + "<td>");
    }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

        


    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    for(int i=0; i<num2.length; i++){
        out.println(num2[i] +  "<th>" +"<td>");
    }
    
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
